package com.devarshi2.android.delhiguide;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.TextView;

public class shops6 extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_shops6);
        String name="CLOSED ON MONDAYS AND OPEN FROM 11AM TO 8PM";
         name=name+"At the Sarojini Nagar Market you get fashionable clothes at affordable prices. Export-surplus garments as well as rejected export clothing come to this market at throwaway prices. That is why product of even reputed brands available here at cheap prices. But don't expect trial or changing rooms at street-side shops. Besides, use your art of haggling. The market remains closed on Mondays. There are different areas within the market. Babu Market houses several sweet shops. The many shoe shops in the vicinity of the market also catch the eye. Subzi Mundi offers the freshest and choicest fruits and fresh vegetables.";
        name=name+"The market which is surrounded by government housing has the following sections, as locals call them. 90% of the shops in SN are family owned.\n" +
                "The Babu Market\n" +
                "Subzi Market\n" +
                "Central Market\n" +
                "Mandir wali side.\n" +
                "Babu Market is located at the north-west corner of Sarojini Nagar Market. It has four rows of enclosed shops facing each other. Most of the shops are garment and clothes shops. The first shop on the corner of Sarojini Nagar which faces the north-east of Babu Market is Mahindra Sweets. This shop is outside the enclosed area of Babu Market. More famously known as Mucchal Halwayi ki Dukaan. A name given to this shop because its owner had big mustaches. After his demise, his children have taken over the business. On rainy days or during evenings crowds line up in front of this shop to buy hot Samosas and Jalebi. This shop is followed by steel utensil shops which draw large crowds during Dhan-teras.\n" +
                "On the north-west corner of the market, the first shop is a shoe shop. This used to be a bakery and general store till the early 1990s. Some other famous shops in Babu Market include Kurta Payjama shops (Lalaji ki Dukan), Chacha Saree, Keval ki Toy Shop, an open-air barber shop, open-air chaye wala, Neelgagan Stationery, meat shops and Kumar Dentist. Most of the shops that are enclosed in rows facing each other are garment shops. Shopping here becomes a challenge during the Summer time when temperatures get into 45 to 48 °C (116 °F). G, H, and I are the nearest Residential block to Babu Market. During evenings, the section of the market that faces the central market lights up with hundreds of street vendors, pop-corn vendors, and other small street sellers who usually carry a small kerosene gas lamp on their carts. There is also a CGHS dispensary just opposite to Babpu Market where government employees can get a free checkup from a 24-hour available doctor. Like any other section of the market, parking is a big problem in Babu Market, especially during evenings.\n" +
                "The far south end of the Sarojini Nagar market is Subzi Market. Subzi is the common Hindi word for vegetables in North India. This Subzi market is famous for its fresh vegetables in South West Delhi. The vegetable vendors shout at the top of their voice to attract customers to their stalls. Some of these vendors get creative with the calls and rhyme them in a comic way.\n" +
                "Subzi market is also the best place to get freshest fruits in South West Delhi at a reasonable price. Customers can bargain with vendors when buying large quantities of fruits or vegetables. There is a parking lot right behind the market facing the Government Girls Senior Secondary School No. 1.\n" +
                "Facing Subzi market is a section of Central Market which is famous for the shops Alpana Traders, Kalpana Traders, Furniture Houses and General Stores where one can buy spice. Till the early 1990s the corner-most shop of the western end of this market used to be a Sweets Shop. After the father’s demise, the younger generation converted this into a garment shop. Right outside this shop however a traditional Tikki and Kulfi vendor continues to sell his famous Tikki and Kulfi. The large central market is shaped like a horizontally extended “I” or “][“. Layout of the market is unique wherein visitors move around in a circle without realizing so. People who get lost sometimes find it hard to believe that by keep going on they will reach the starting point of their trip. Shops are lined up in rows and there is a newly constructed open-air path-way in front of the shops for customers to move through the crowds to get into each shop. These pathways are also largely occupied by illegal street vendors. Shops have a front opening, and a back opening. The back-streets (galiyan) of SN market are just as crowded and busy as the path-ways in front of the shops. In fact the most famous Export Bazaar/Market for clothes is located in the back-streets of the market which is closer to Subzi market. On one side of the central market there are famous bakery shops like US POLO Exclusive, Mohan Restaurant, Paradise Sarees, Grover Furniture, Capri store and Atta Chakki. On the other side of the central market which faces the Hanuman Temple are the Lahori Restaurant, Electronic Stores, Ushnak Milk Dairy, Optics Shops, New Photo Life, Band Box Drycleaners and Pharmacy shops. This part of the market boasts of big showrooms like Kins Footwear, Nike Brand store and Balaji Electricals.\n" +
                "The export lane compromises of great bags store and one of the best place to buy bags in Sarojini nagar is Old Tree which keeps all kind of leather and non leather bags. This store is right in the main export lane just besides a tree.\n" +
                "The North side of central SN market mostly has footwear shops. Some of the famous shops in this section of the market are Paul Shoes, Paul Photo Studios, Om Boot House, Liberty and Bata Shoes, Woodland Shoes and Reebok Shoes. There are also a few famous leather belt vendors who occupy the space near the large arches where the you may still see the decades-old sign “SAROJINI NAGAR”. Some of the letters in this sign were already missing and may be as it stands today, these letters may not even be there.\n" +
                "Sarojini Nagar was also a hot bed of BJP, RSS and VHP activities. The annual dussera festival is still celebrated with the nine days of Ram-Lila followed by Ravan Dahan. In early 1980s and 1990s RSS Svayam Sevaks (activists) could be seen holding Shakhas (daily gatherings) in their uniquely recognizable short-pants and white shirts. Some of the parks in the surrounding area are named after famous freedom fighters and religious leaders such as Swami Vivekanand Park. In late 70s or eighties this park was also called the Fountain Garden or (Hindi: Fuarey wala park), since it had water fountains and lights that would attract local visitors and kids during evening hours. The park got renovated and landscaped around 2007 and provides respite to tired shopaholics/joggers/residents.\n" +
                "The Sarojini Market remains closed on Mondays. Sarojini Nagar Market opens up around 11 A.M. and shut down around 8 or 9 P.M.[3]\n" +
                "Sarojini Nagar is a place that is located in the south west District of Delhi state in India. The vicinity of Sarojini Nagar Market is very much developed and is the cleanest area and it is most popular due to its market. At the Sarojini Nagar Market you get stylish clothes at reasonable prices.";
        TextView tv=(TextView)findViewById(R.id.textView1);
        tv.setText(name);
    }
}
